---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.19
  labels:
    derrick.service: derrick-nodejs-demo
  name: derrick-nodejs-demo
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    derrick.service: derrick-nodejs-demo
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.19
  labels:
    derrick.service: derrick-nodejs-demo
  name: derrick-nodejs-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: derrick-nodejs-demo
    spec:
      containers:
      - image: 192.168.0.31/dev/nodejs
        name: web
        ports:
        - containerPort: 3000